### PR TITLE
DP: coin change problem

### PR DESCRIPTION
**Pull request by DeepakRathore2k1**

### CODE REVIEW

**Comment by DeepakRathore2k1** [comment]
coin change problem

**Comment by sushish-kumar** [comment]
Hello Deepak,
Would yo please add comments into your code wherever appropriate to improve the readability of your code? Also It would be great if you would write the problem statement at top.

Thanks.

**Comment by DeepakRathore2k1** [comment]
yeah, sure

**Comment by sushish-kumar** [comment]
Great. merging the PR.

**Pull request merged**
